import warnings
from litellm.exceptions import RateLimitError, Timeout, APIError, BadRequestError
from financial_agents.src.financial_agents.crew_ai import FinancialAgents

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

def crew_ai_project(prompt, conteudo):
    try: 
        crew_instance = FinancialAgents()
        
        result = crew_instance.crew().kickoff(inputs={
                                                        "prompt": prompt,
                                                        "conteudo": conteudo,
                                                    })
        return result
    
    except RateLimitError as rle:
        return f""" ###üö¶ Limite de requisi√ß√µes atingido! 
            Tente novamente em alguns instantes. 
            (Modelo: {rle.model}) (Mensagem: {rle.message})"""
        

    except Timeout as to:
        return f"""‚è≥ A requisi√ß√£o demorou mais do que o esperado e foi cancelada. 
            Verifique sua conex√£o ou tente novamente.
            \nDetalhes t√©cnicos: {to}"""
        

    except APIError as apierror:
        return f"""‚ö†Ô∏è Ocorreu um erro ao se comunicar com a API do modelo. 
            Isso pode ser tempor√°rio. Tente novamente mais tarde.
            \nDetalhes t√©cnicos: {apierror}"""
        

    except BadRequestError as bre:
        return """‚ùå A solicita√ß√£o enviada ao modelo n√£o foi aceita (Bad Request). 
            Isso geralmente acontece por par√¢metros incorretos ou incompatibilidade com o modelo escolhido.
            f\nDetalhes t√©cnicos: {bre}"""
        
    except Exception as e:
        return f" Aconteceu o erro {e.__cause__}"
